from app import create_app
from cloudflare_extension import init_cloudflare_center
from configuration_extension import init_configuration_center
from database_browser_extension import init_database_browser
from deployment_ui_extension import init_deployment_ui
from docker_center_extension import init_docker_center
from file_browser_extension import init_file_browser
from github_extension import init_github_center
from logging_extension import init_structured_logging
from maintenance_extension import init_maintenance
from migration_extension import init_migrations
from module_registry_extension import init_module_registry
from network_center_extension import init_network_center
from node_hardware_extension import init_node_hardware_center
from observability_extension import init_observability
from operations_timeline_extension import init_operations_timeline
from plugin_extension import init_plugin_center
from rbac_extension import init_rbac
from readiness_extension import init_readiness_center
from release_extension import init_release_center
from restore_ui_extension import init_restore_ui
from security_extension import init_security
from service_health_extension import init_service_health_center
from ssh_console_extension import init_ssh_console
from storage_center_extension import init_storage_center
from support_bundle_extension import init_support_bundle_center
from update_center_extension import init_update_center

app = create_app()
init_structured_logging(app)
init_migrations(app)
init_security(app)
init_rbac(app)
init_maintenance(app)
init_github_center(app)
init_configuration_center(app)
init_observability(app)
init_database_browser(app)
init_file_browser(app)
init_cloudflare_center(app)
init_plugin_center(app)
init_deployment_ui(app)
init_restore_ui(app)
init_docker_center(app)
init_operations_timeline(app)
init_ssh_console(app)
init_readiness_center(app)
init_node_hardware_center(app)
init_network_center(app)
init_storage_center(app)
init_service_health_center(app)
init_update_center(app)
init_support_bundle_center(app)
init_release_center(app)
init_module_registry(app)
