from app import create_app
from cloudflare_extension import init_cloudflare_center
from configuration_extension import init_configuration_center
from database_browser_extension import init_database_browser
from deployment_ui_extension import init_deployment_ui
from file_browser_extension import init_file_browser
from github_extension import init_github_center
from logging_extension import init_structured_logging
from maintenance_extension import init_maintenance
from migration_extension import init_migrations
from observability_extension import init_observability
from plugin_extension import init_plugin_center
from rbac_extension import init_rbac
from restore_ui_extension import init_restore_ui
from security_extension import init_security

app = create_app()
init_structured_logging(app)
init_migrations(app)
init_security(app)
init_rbac(app)
init_maintenance(app)
init_github_center(app)
init_configuration_center(app)
init_observability(app)
init_database_browser(app)
init_file_browser(app)
init_cloudflare_center(app)
init_plugin_center(app)
init_deployment_ui(app)
init_restore_ui(app)
